// ─────────────────────────────────────────────────────────────────────
// Biblioteca Inteligente Fit-K v1.0 — 81 ejercicios base.
// Generado desde FIT-K_Biblioteca_Inteligente_v1.0.xlsx (hoja "Biblioteca").
// La Biblioteca describe; el Motor (fitkMotor.ts) decide. No editar a mano
// salvo para corregir datos — cualquier cambio de criterio va en el Motor.
// ─────────────────────────────────────────────────────────────────────

export interface SecondaryMuscle {
  muscle: string;
  coefficient: number; // 0.5 = indirecto relevante, 0 = secundario menor
}

export interface LibraryExercise {
  id: string;
  name: string;
  block: string;
  family: string;
  movementPattern: string;
  compatibleRoles: string[]; // Principal | Complementario | Aislamiento | Estabilidad | Control
  equipment: string;
  loadSource: string;
  laterality: string;
  primaryMuscle: string;
  secondaryMuscles: SecondaryMuscle[];
  accessibility: string;       // Alta | Media-Alta | Media | Baja-Media | Baja
  strengthRequirement: string; // Alta | Media | Baja-Media | Baja | Variable
  scalability: string;         // Alta | Media
  stability: string;           // Alta | Media-Alta | Media | Baja-Media
  fatigueCost: string;         // Alta | Media-Alta | Media | Baja-Media | Baja
  progressionSuitability: string;
  nearFailureSuitability: string;
  repRangeV1: [number, number];
  restRangeSeconds: [number, number];
  setupCost: string;         // Alto | Medio | Bajo | Mínimo
  executionTimeCost: string; // Alto | Medio-Alto | Medio | Bajo-Medio | Bajo
  densitySuitability: string;
  substitutionFamily: string;
  motorNotes?: string;
}

export const LIBRARY: LibraryExercise[] = [
  {
    id: "chest_barbell_bench_press", name: "Press banca barra", block: "Pecho", family: "Press horizontal",
    movementPattern: "Empuje horizontal", compatibleRoles: ["Principal"],
    equipment: "Barra+banco+rack", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Pecho", secondaryMuscles: [{ muscle: "Tríceps", coefficient: 0.5 }, { muscle: "deltoide anterior", coefficient: 0.5 }],
    accessibility: "Media", strengthRequirement: "Baja-Media", scalability: "Alta",
    stability: "Media", fatigueCost: "Media-Alta", progressionSuitability: "Alta",
    nearFailureSuitability: "Media", repRangeV1: [5, 12],
    restRangeSeconds: [120, 180], setupCost: "Alto",
    executionTimeCost: "Medio", densitySuitability: "Baja-Media", substitutionFamily: "Press horizontal",
    motorNotes: "Sin bonus por barra",
  },
  {
    id: "chest_db_bench_press", name: "Press banca mancuernas", block: "Pecho", family: "Press horizontal",
    movementPattern: "Empuje horizontal", compatibleRoles: ["Principal", "Complementario"],
    equipment: "Mancuernas+banco", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Pecho", secondaryMuscles: [{ muscle: "Tríceps", coefficient: 0.5 }, { muscle: "deltoide anterior", coefficient: 0.5 }],
    accessibility: "Media", strengthRequirement: "Baja-Media", scalability: "Alta",
    stability: "Media", fatigueCost: "Media", progressionSuitability: "Media-Alta",
    nearFailureSuitability: "Media-Alta", repRangeV1: [6, 15],
    restRangeSeconds: [90, 180], setupCost: "Medio",
    executionTimeCost: "Medio", densitySuitability: "Media", substitutionFamily: "Press horizontal",
  },
  {
    id: "chest_machine_press", name: "Press pecho máquina", block: "Pecho", family: "Press horizontal",
    movementPattern: "Empuje horizontal", compatibleRoles: ["Principal", "Complementario"],
    equipment: "Máquina", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Pecho", secondaryMuscles: [{ muscle: "Tríceps", coefficient: 0.5 }, { muscle: "deltoide anterior", coefficient: 0.5 }],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Media", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [6, 15],
    restRangeSeconds: [90, 180], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Press horizontal",
  },
  {
    id: "chest_incline_barbell", name: "Press inclinado barra", block: "Pecho", family: "Press inclinado",
    movementPattern: "Empuje inclinado", compatibleRoles: ["Principal"],
    equipment: "Barra+banco", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Pecho clavicular", secondaryMuscles: [{ muscle: "Tríceps", coefficient: 0.5 }, { muscle: "deltoide anterior", coefficient: 0.5 }],
    accessibility: "Media", strengthRequirement: "Baja-Media", scalability: "Alta",
    stability: "Media", fatigueCost: "Media-Alta", progressionSuitability: "Alta",
    nearFailureSuitability: "Media", repRangeV1: [5, 12],
    restRangeSeconds: [120, 180], setupCost: "Alto",
    executionTimeCost: "Medio", densitySuitability: "Baja-Media", substitutionFamily: "Press inclinado",
  },
  {
    id: "chest_incline_db", name: "Press inclinado mancuernas", block: "Pecho", family: "Press inclinado",
    movementPattern: "Empuje inclinado", compatibleRoles: ["Principal", "Complementario"],
    equipment: "Mancuernas+banco", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Pecho clavicular", secondaryMuscles: [{ muscle: "Tríceps", coefficient: 0.5 }, { muscle: "deltoide anterior", coefficient: 0.5 }],
    accessibility: "Media", strengthRequirement: "Baja-Media", scalability: "Alta",
    stability: "Media", fatigueCost: "Media", progressionSuitability: "Media-Alta",
    nearFailureSuitability: "Media-Alta", repRangeV1: [6, 15],
    restRangeSeconds: [90, 180], setupCost: "Medio",
    executionTimeCost: "Medio", densitySuitability: "Media", substitutionFamily: "Press inclinado",
  },
  {
    id: "chest_incline_machine", name: "Press inclinado máquina", block: "Pecho", family: "Press inclinado",
    movementPattern: "Empuje inclinado", compatibleRoles: ["Principal", "Complementario"],
    equipment: "Máquina", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Pecho clavicular", secondaryMuscles: [{ muscle: "Tríceps", coefficient: 0.5 }, { muscle: "deltoide anterior", coefficient: 0.5 }],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Media", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [6, 15],
    restRangeSeconds: [90, 180], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Press inclinado",
  },
  {
    id: "chest_cable_fly", name: "Aperturas polea", block: "Pecho", family: "Aducción horizontal",
    movementPattern: "Aducción horizontal", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Polea", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Pecho", secondaryMuscles: [],
    accessibility: "Media-Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Media-Alta", fatigueCost: "Baja", progressionSuitability: "Media",
    nearFailureSuitability: "Alta", repRangeV1: [10, 20],
    restRangeSeconds: [60, 120], setupCost: "Medio",
    executionTimeCost: "Bajo-Medio", densitySuitability: "Alta", substitutionFamily: "Aducción pecho",
  },
  {
    id: "chest_pec_deck", name: "Peck deck", block: "Pecho", family: "Aducción horizontal",
    movementPattern: "Aducción horizontal", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Máquina", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Pecho", secondaryMuscles: [],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja", progressionSuitability: "Media-Alta",
    nearFailureSuitability: "Alta", repRangeV1: [8, 20],
    restRangeSeconds: [60, 120], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Aducción pecho",
  },
  {
    id: "chest_pushup", name: "Flexiones", block: "Pecho", family: "Press horizontal",
    movementPattern: "Empuje horizontal", compatibleRoles: ["Principal", "Complementario"],
    equipment: "Peso corporal", loadSource: "Corporal+opcional", laterality: "Bilateral",
    primaryMuscle: "Pecho", secondaryMuscles: [{ muscle: "Tríceps", coefficient: 0.5 }, { muscle: "deltoide anterior", coefficient: 0.5 }],
    accessibility: "Alta", strengthRequirement: "Variable", scalability: "Alta",
    stability: "Media-Alta", fatigueCost: "Baja-Media", progressionSuitability: "Media",
    nearFailureSuitability: "Alta", repRangeV1: [0, 0],
    restRangeSeconds: [60, 180], setupCost: "Mínimo",
    executionTimeCost: "Bajo-Medio", densitySuitability: "Alta", substitutionFamily: "Press horizontal",
    motorNotes: "Peso corporal ≠ fácil",
  },
  {
    id: "back_lat_pulldown", name: "Jalón al pecho", block: "Espalda", family: "Tirón vertical",
    movementPattern: "Tirón vertical", compatibleRoles: ["Principal"],
    equipment: "Polea/máquina", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Dorsal", secondaryMuscles: [{ muscle: "Bíceps", coefficient: 0.5 }],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Media", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [6, 15],
    restRangeSeconds: [90, 180], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Media-Alta", substitutionFamily: "Tirón vertical",
  },
  {
    id: "back_neutral_pulldown", name: "Jalón neutro/estrecho", block: "Espalda", family: "Tirón vertical",
    movementPattern: "Tirón vertical", compatibleRoles: ["Principal", "Complementario"],
    equipment: "Polea/máquina", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Dorsal", secondaryMuscles: [{ muscle: "Bíceps", coefficient: 0.5 }],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Media", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [6, 15],
    restRangeSeconds: [90, 180], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Media-Alta", substitutionFamily: "Tirón vertical",
    motorNotes: "Agarre puede ser variante",
  },
  {
    id: "back_pullup", name: "Dominadas", block: "Espalda", family: "Tirón vertical",
    movementPattern: "Tirón vertical", compatibleRoles: ["Principal"],
    equipment: "Barra dominadas", loadSource: "Corporal+opcional", laterality: "Bilateral",
    primaryMuscle: "Dorsal", secondaryMuscles: [{ muscle: "Bíceps", coefficient: 0.5 }],
    accessibility: "Media", strengthRequirement: "Alta", scalability: "Media",
    stability: "Media", fatigueCost: "Media-Alta", progressionSuitability: "Media-Alta",
    nearFailureSuitability: "Media-Alta", repRangeV1: [0, 0],
    restRangeSeconds: [120, 180], setupCost: "Bajo",
    executionTimeCost: "Medio", densitySuitability: "Baja-Media", substitutionFamily: "Tirón vertical",
  },
  {
    id: "back_assisted_pullup", name: "Dominadas asistidas", block: "Espalda", family: "Tirón vertical",
    movementPattern: "Tirón vertical", compatibleRoles: ["Principal", "Complementario"],
    equipment: "Máquina/asistencia segura", loadSource: "Corporal asistida", laterality: "Bilateral",
    primaryMuscle: "Dorsal", secondaryMuscles: [{ muscle: "Bíceps", coefficient: 0.5 }],
    accessibility: "Media-Alta", strengthRequirement: "Media", scalability: "Alta",
    stability: "Alta", fatigueCost: "Media", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [6, 15],
    restRangeSeconds: [90, 180], setupCost: "Medio",
    executionTimeCost: "Medio", densitySuitability: "Media", substitutionFamily: "Tirón vertical",
  },
  {
    id: "back_cable_row", name: "Remo sentado polea", block: "Espalda", family: "Tirón horizontal",
    movementPattern: "Tirón horizontal", compatibleRoles: ["Principal", "Complementario"],
    equipment: "Polea", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Espalda media/dorsal", secondaryMuscles: [{ muscle: "Bíceps", coefficient: 0.5 }, { muscle: "deltoide posterior", coefficient: 0 }],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Media", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [6, 15],
    restRangeSeconds: [90, 180], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Media-Alta", substitutionFamily: "Tirón horizontal",
  },
  {
    id: "back_supported_row", name: "Remo máquina pecho apoyado", block: "Espalda", family: "Tirón horizontal",
    movementPattern: "Tirón horizontal", compatibleRoles: ["Principal", "Complementario"],
    equipment: "Máquina", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Espalda media/dorsal", secondaryMuscles: [{ muscle: "Bíceps", coefficient: 0.5 }, { muscle: "deltoide posterior", coefficient: 0 }],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja-Media", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [6, 15],
    restRangeSeconds: [90, 180], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Tirón horizontal",
  },
  {
    id: "back_onearm_db_row", name: "Remo mancuerna unilateral", block: "Espalda", family: "Tirón horizontal",
    movementPattern: "Tirón horizontal", compatibleRoles: ["Principal", "Complementario"],
    equipment: "Mancuerna+apoyo", loadSource: "Externa", laterality: "Unilateral",
    primaryMuscle: "Dorsal/espalda media", secondaryMuscles: [{ muscle: "Bíceps", coefficient: 0.5 }],
    accessibility: "Media", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Media-Alta", fatigueCost: "Media", progressionSuitability: "Alta",
    nearFailureSuitability: "Media-Alta", repRangeV1: [6, 15],
    restRangeSeconds: [90, 180], setupCost: "Medio",
    executionTimeCost: "Alto", densitySuitability: "Media", substitutionFamily: "Tirón horizontal",
    motorNotes: "Coste unilateral",
  },
  {
    id: "back_barbell_row", name: "Remo barra", block: "Espalda", family: "Tirón horizontal",
    movementPattern: "Tirón horizontal", compatibleRoles: ["Principal"],
    equipment: "Barra", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Espalda media/dorsal", secondaryMuscles: [{ muscle: "Bíceps", coefficient: 0.5 }, { muscle: "erectores estabilizan", coefficient: 0 }],
    accessibility: "Media", strengthRequirement: "Baja-Media", scalability: "Alta",
    stability: "Baja-Media", fatigueCost: "Alta", progressionSuitability: "Alta",
    nearFailureSuitability: "Media", repRangeV1: [5, 12],
    restRangeSeconds: [120, 180], setupCost: "Medio",
    executionTimeCost: "Medio", densitySuitability: "Baja", substitutionFamily: "Tirón horizontal",
  },
  {
    id: "back_tbar_row", name: "Remo T", block: "Espalda", family: "Tirón horizontal",
    movementPattern: "Tirón horizontal", compatibleRoles: ["Principal"],
    equipment: "T-bar/máquina", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Espalda media/dorsal", secondaryMuscles: [{ muscle: "Bíceps", coefficient: 0.5 }],
    accessibility: "Media-Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Media-Alta", fatigueCost: "Media-Alta", progressionSuitability: "Alta",
    nearFailureSuitability: "Media-Alta", repRangeV1: [6, 15],
    restRangeSeconds: [90, 180], setupCost: "Medio",
    executionTimeCost: "Medio", densitySuitability: "Media", substitutionFamily: "Tirón horizontal",
  },
  {
    id: "back_cable_pullover", name: "Pullover polea", block: "Espalda", family: "Extensión hombro",
    movementPattern: "Extensión hombro", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Polea", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Dorsal", secondaryMuscles: [],
    accessibility: "Media-Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Media-Alta", fatigueCost: "Baja", progressionSuitability: "Media",
    nearFailureSuitability: "Alta", repRangeV1: [10, 20],
    restRangeSeconds: [60, 120], setupCost: "Medio",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Extensión hombro",
  },
  {
    id: "back_machine_pullover", name: "Pullover máquina", block: "Espalda", family: "Extensión hombro",
    movementPattern: "Extensión hombro", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Máquina", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Dorsal", secondaryMuscles: [],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja", progressionSuitability: "Media-Alta",
    nearFailureSuitability: "Alta", repRangeV1: [8, 20],
    restRangeSeconds: [60, 120], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Extensión hombro",
  },
  {
    id: "shoulder_barbell_press", name: "Press militar barra", block: "Hombro", family: "Press vertical",
    movementPattern: "Empuje vertical", compatibleRoles: ["Principal"],
    equipment: "Barra+rack", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Deltoide anterior", secondaryMuscles: [{ muscle: "Tríceps", coefficient: 0.5 }, { muscle: "lateral relevante", coefficient: 0 }],
    accessibility: "Media", strengthRequirement: "Baja-Media", scalability: "Alta",
    stability: "Media", fatigueCost: "Media-Alta", progressionSuitability: "Alta",
    nearFailureSuitability: "Media", repRangeV1: [5, 12],
    restRangeSeconds: [120, 180], setupCost: "Alto",
    executionTimeCost: "Medio", densitySuitability: "Baja-Media", substitutionFamily: "Press vertical",
  },
  {
    id: "shoulder_db_press", name: "Press hombro mancuernas", block: "Hombro", family: "Press vertical",
    movementPattern: "Empuje vertical", compatibleRoles: ["Principal"],
    equipment: "Mancuernas", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Deltoide anterior", secondaryMuscles: [{ muscle: "Tríceps", coefficient: 0.5 }, { muscle: "lateral relevante", coefficient: 0 }],
    accessibility: "Media", strengthRequirement: "Baja-Media", scalability: "Alta",
    stability: "Media", fatigueCost: "Media", progressionSuitability: "Media-Alta",
    nearFailureSuitability: "Media-Alta", repRangeV1: [6, 15],
    restRangeSeconds: [90, 180], setupCost: "Medio",
    executionTimeCost: "Medio", densitySuitability: "Media", substitutionFamily: "Press vertical",
  },
  {
    id: "shoulder_machine_press", name: "Press hombro máquina", block: "Hombro", family: "Press vertical",
    movementPattern: "Empuje vertical", compatibleRoles: ["Principal", "Complementario"],
    equipment: "Máquina", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Deltoide anterior", secondaryMuscles: [{ muscle: "Tríceps", coefficient: 0.5 }, { muscle: "lateral relevante", coefficient: 0 }],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Media", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [6, 15],
    restRangeSeconds: [90, 180], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Press vertical",
  },
  {
    id: "shoulder_db_lateral", name: "Elevación lateral mancuernas", block: "Hombro", family: "Abducción",
    movementPattern: "Abducción hombro", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Mancuernas", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Deltoide lateral", secondaryMuscles: [],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Media-Alta", fatigueCost: "Baja", progressionSuitability: "Media",
    nearFailureSuitability: "Alta", repRangeV1: [10, 20],
    restRangeSeconds: [60, 120], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Abducción hombro",
  },
  {
    id: "shoulder_cable_lateral", name: "Elevación lateral polea", block: "Hombro", family: "Abducción",
    movementPattern: "Abducción hombro", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Polea", loadSource: "Externa", laterality: "Unilateral",
    primaryMuscle: "Deltoide lateral", secondaryMuscles: [],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja", progressionSuitability: "Media",
    nearFailureSuitability: "Alta", repRangeV1: [10, 20],
    restRangeSeconds: [60, 120], setupCost: "Medio",
    executionTimeCost: "Medio-Alto", densitySuitability: "Media-Alta", substitutionFamily: "Abducción hombro",
  },
  {
    id: "shoulder_machine_lateral", name: "Elevación lateral máquina", block: "Hombro", family: "Abducción",
    movementPattern: "Abducción hombro", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Máquina", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Deltoide lateral", secondaryMuscles: [],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [10, 20],
    restRangeSeconds: [60, 120], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Abducción hombro",
  },
  {
    id: "shoulder_reverse_pecdeck", name: "Reverse pec deck", block: "Hombro", family: "Deltoide posterior",
    movementPattern: "Abducción horizontal", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Máquina", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Deltoide posterior", secondaryMuscles: [{ muscle: "Trapecio/escapulares", coefficient: 0 }],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [10, 20],
    restRangeSeconds: [60, 120], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Deltoide posterior",
  },
  {
    id: "shoulder_rear_delt_db", name: "Pájaros mancuernas", block: "Hombro", family: "Deltoide posterior",
    movementPattern: "Abducción horizontal", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Mancuernas", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Deltoide posterior", secondaryMuscles: [{ muscle: "Trapecio/escapulares", coefficient: 0 }],
    accessibility: "Media", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Media", fatigueCost: "Baja-Media", progressionSuitability: "Media",
    nearFailureSuitability: "Alta", repRangeV1: [10, 20],
    restRangeSeconds: [60, 120], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Deltoide posterior",
  },
  {
    id: "shoulder_facepull", name: "Face pull", block: "Hombro", family: "Tirón alto/control",
    movementPattern: "Tirón alto", compatibleRoles: ["Complementario", "Control"],
    equipment: "Polea", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Deltoide posterior", secondaryMuscles: [{ muscle: "Trapecio/escapulares", coefficient: 0 }],
    accessibility: "Media", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Media-Alta", fatigueCost: "Baja", progressionSuitability: "Media",
    nearFailureSuitability: "Alta", repRangeV1: [10, 20],
    restRangeSeconds: [60, 120], setupCost: "Medio",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Deltoide posterior/escapular",
  },
  {
    id: "trap_db_shrug", name: "Encogimientos mancuernas", block: "Trapecio", family: "Elevación escapular",
    movementPattern: "Elevación escapular", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Mancuernas", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Trapecio superior", secondaryMuscles: [{ muscle: "Agarre relevante", coefficient: 0 }],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja-Media", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [8, 20],
    restRangeSeconds: [60, 120], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Elevación escapular",
  },
  {
    id: "trap_barbell_shrug", name: "Encogimientos barra", block: "Trapecio", family: "Elevación escapular",
    movementPattern: "Elevación escapular", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Barra", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Trapecio superior", secondaryMuscles: [{ muscle: "Agarre relevante", coefficient: 0 }],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Media", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [6, 20],
    restRangeSeconds: [60, 120], setupCost: "Medio",
    executionTimeCost: "Bajo", densitySuitability: "Media-Alta", substitutionFamily: "Elevación escapular",
  },
  {
    id: "trap_machine_shrug", name: "Encogimientos máquina/Smith", block: "Trapecio", family: "Elevación escapular",
    movementPattern: "Elevación escapular", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Máquina/Smith", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Trapecio superior", secondaryMuscles: [{ muscle: "Agarre relevante", coefficient: 0 }],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja-Media", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [8, 20],
    restRangeSeconds: [60, 120], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Elevación escapular",
  },
  {
    id: "biceps_bar_curl", name: "Curl barra/EZ", block: "Bíceps", family: "Flexión codo",
    movementPattern: "Flexión codo", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Barra/EZ", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Bíceps", secondaryMuscles: [{ muscle: "Antebrazo", coefficient: 0 }],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja-Media", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [6, 15],
    restRangeSeconds: [60, 120], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Flexión codo",
    motorNotes: "Recta/EZ puede ser configuración",
  },
  {
    id: "biceps_db_curl", name: "Curl mancuernas", block: "Bíceps", family: "Flexión codo",
    movementPattern: "Flexión codo", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Mancuernas", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Bíceps", secondaryMuscles: [{ muscle: "Antebrazo", coefficient: 0 }],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Media-Alta", fatigueCost: "Baja", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [8, 15],
    restRangeSeconds: [60, 120], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Flexión codo",
  },
  {
    id: "biceps_alt_curl", name: "Curl alterno", block: "Bíceps", family: "Flexión codo",
    movementPattern: "Flexión codo", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Mancuernas", loadSource: "Externa", laterality: "Alterno",
    primaryMuscle: "Bíceps", secondaryMuscles: [{ muscle: "Antebrazo", coefficient: 0 }],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Media-Alta", fatigueCost: "Baja", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [8, 15],
    restRangeSeconds: [60, 120], setupCost: "Bajo",
    executionTimeCost: "Medio", densitySuitability: "Alta", substitutionFamily: "Flexión codo",
  },
  {
    id: "biceps_hammer", name: "Curl martillo", block: "Bíceps", family: "Flexión codo neutra",
    movementPattern: "Flexión codo", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Mancuernas", loadSource: "Externa", laterality: "Bilateral/alterno",
    primaryMuscle: "Braquial/bíceps", secondaryMuscles: [{ muscle: "Braquiorradial", coefficient: 0 }],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [8, 15],
    restRangeSeconds: [60, 120], setupCost: "Bajo",
    executionTimeCost: "Bajo-Medio", densitySuitability: "Alta", substitutionFamily: "Flexión codo",
  },
  {
    id: "biceps_cable", name: "Curl polea", block: "Bíceps", family: "Flexión codo",
    movementPattern: "Flexión codo", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Polea", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Bíceps", secondaryMuscles: [{ muscle: "Antebrazo", coefficient: 0 }],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [8, 20],
    restRangeSeconds: [60, 120], setupCost: "Medio",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Flexión codo",
  },
  {
    id: "biceps_preacher", name: "Curl predicador", block: "Bíceps", family: "Flexión codo",
    movementPattern: "Flexión codo", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Banco/máquina", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Bíceps", secondaryMuscles: [],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [8, 15],
    restRangeSeconds: [60, 120], setupCost: "Medio",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Flexión codo",
  },
  {
    id: "triceps_pushdown", name: "Extensión tríceps polea", block: "Tríceps", family: "Extensión codo",
    movementPattern: "Extensión codo", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Polea", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Tríceps", secondaryMuscles: [],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [8, 20],
    restRangeSeconds: [60, 120], setupCost: "Medio",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Extensión codo",
    motorNotes: "Cuerda/barra = configuración",
  },
  {
    id: "triceps_overhead_cable", name: "Extensión tríceps overhead polea", block: "Tríceps", family: "Extensión codo overhead",
    movementPattern: "Extensión codo", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Polea", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Tríceps", secondaryMuscles: [],
    accessibility: "Media-Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Media-Alta", fatigueCost: "Baja", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [8, 20],
    restRangeSeconds: [60, 120], setupCost: "Medio",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Extensión codo overhead",
  },
  {
    id: "triceps_overhead_db", name: "Extensión overhead mancuerna", block: "Tríceps", family: "Extensión codo overhead",
    movementPattern: "Extensión codo", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Mancuerna", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Tríceps", secondaryMuscles: [],
    accessibility: "Media", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Media", fatigueCost: "Baja", progressionSuitability: "Media-Alta",
    nearFailureSuitability: "Media-Alta", repRangeV1: [8, 20],
    restRangeSeconds: [60, 120], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Extensión codo overhead",
  },
  {
    id: "triceps_french_press", name: "Press francés", block: "Tríceps", family: "Extensión codo",
    movementPattern: "Extensión codo", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Barra/EZ/mancuernas", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Tríceps", secondaryMuscles: [],
    accessibility: "Media", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Media", fatigueCost: "Baja-Media", progressionSuitability: "Alta",
    nearFailureSuitability: "Media", repRangeV1: [6, 15],
    restRangeSeconds: [60, 120], setupCost: "Medio",
    executionTimeCost: "Bajo", densitySuitability: "Media-Alta", substitutionFamily: "Extensión codo",
  },
  {
    id: "triceps_closegrip_press", name: "Press cerrado", block: "Tríceps", family: "Press dominante tríceps",
    movementPattern: "Empuje horizontal", compatibleRoles: ["Principal", "Complementario"],
    equipment: "Barra+banco", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Tríceps", secondaryMuscles: [{ muscle: "Pecho", coefficient: 0.5 }, { muscle: "deltoide anterior", coefficient: 0 }],
    accessibility: "Media", strengthRequirement: "Baja-Media", scalability: "Alta",
    stability: "Media", fatigueCost: "Media-Alta", progressionSuitability: "Alta",
    nearFailureSuitability: "Media", repRangeV1: [5, 12],
    restRangeSeconds: [120, 180], setupCost: "Alto",
    executionTimeCost: "Medio", densitySuitability: "Baja-Media", substitutionFamily: "Press dominante tríceps",
  },
  {
    id: "triceps_dip", name: "Fondos", block: "Tríceps", family: "Empuje corporal",
    movementPattern: "Empuje", compatibleRoles: ["Principal", "Complementario"],
    equipment: "Paralelas/asistida", loadSource: "Corporal+opcional", laterality: "Bilateral",
    primaryMuscle: "Tríceps", secondaryMuscles: [{ muscle: "Pecho y deltoide anterior", coefficient: 0 }],
    accessibility: "Media", strengthRequirement: "Alta", scalability: "Media",
    stability: "Media", fatigueCost: "Media-Alta", progressionSuitability: "Media-Alta",
    nearFailureSuitability: "Media", repRangeV1: [0, 0],
    restRangeSeconds: [120, 180], setupCost: "Bajo",
    executionTimeCost: "Medio", densitySuitability: "Baja-Media", substitutionFamily: "Empuje dominante tríceps",
  },
  {
    id: "quad_back_squat", name: "Sentadilla barra", block: "Pierna", family: "Dominante rodilla",
    movementPattern: "Sentadilla", compatibleRoles: ["Principal"],
    equipment: "Barra+rack", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Cuádriceps", secondaryMuscles: [{ muscle: "Glúteos", coefficient: 0 }, { muscle: "erectores estabilizan", coefficient: 0 }],
    accessibility: "Media", strengthRequirement: "Baja-Media", scalability: "Alta",
    stability: "Baja-Media", fatigueCost: "Alta", progressionSuitability: "Alta",
    nearFailureSuitability: "Media", repRangeV1: [5, 12],
    restRangeSeconds: [120, 240], setupCost: "Alto",
    executionTimeCost: "Medio", densitySuitability: "Baja", substitutionFamily: "Dominante rodilla",
  },
  {
    id: "quad_smith_squat", name: "Sentadilla Smith", block: "Pierna", family: "Dominante rodilla",
    movementPattern: "Sentadilla", compatibleRoles: ["Principal"],
    equipment: "Smith", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Cuádriceps", secondaryMuscles: [{ muscle: "Glúteos", coefficient: 0 }],
    accessibility: "Media-Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Media-Alta", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [6, 15],
    restRangeSeconds: [120, 180], setupCost: "Medio",
    executionTimeCost: "Medio", densitySuitability: "Media", substitutionFamily: "Dominante rodilla",
  },
  {
    id: "quad_bodyweight_squat", name: "Sentadilla peso corporal", block: "Pierna", family: "Dominante rodilla",
    movementPattern: "Sentadilla", compatibleRoles: ["Principal", "Complementario"],
    equipment: "Peso corporal", loadSource: "Corporal+opcional", laterality: "Bilateral",
    primaryMuscle: "Cuádriceps", secondaryMuscles: [{ muscle: "Glúteos", coefficient: 0 }],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja-Media", progressionSuitability: "Media",
    nearFailureSuitability: "Alta", repRangeV1: [0, 0],
    restRangeSeconds: [60, 120], setupCost: "Mínimo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Dominante rodilla",
  },
  {
    id: "quad_hack", name: "Hack squat", block: "Pierna", family: "Dominante rodilla",
    movementPattern: "Sentadilla/prensa", compatibleRoles: ["Principal"],
    equipment: "Máquina", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Cuádriceps", secondaryMuscles: [{ muscle: "Glúteos", coefficient: 0 }],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Alta", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [6, 15],
    restRangeSeconds: [120, 180], setupCost: "Bajo",
    executionTimeCost: "Medio", densitySuitability: "Media", substitutionFamily: "Dominante rodilla",
  },
  {
    id: "quad_legpress", name: "Prensa", block: "Pierna", family: "Dominante rodilla",
    movementPattern: "Prensa", compatibleRoles: ["Principal"],
    equipment: "Máquina", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Cuádriceps", secondaryMuscles: [{ muscle: "Glúteos", coefficient: 0 }],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Media-Alta", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [6, 20],
    restRangeSeconds: [120, 180], setupCost: "Bajo",
    executionTimeCost: "Medio", densitySuitability: "Media", substitutionFamily: "Dominante rodilla",
  },
  {
    id: "quad_extension", name: "Extensión cuádriceps", block: "Pierna", family: "Extensión rodilla",
    movementPattern: "Extensión rodilla", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Máquina", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Cuádriceps", secondaryMuscles: [],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [8, 20],
    restRangeSeconds: [60, 120], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Extensión rodilla",
  },
  {
    id: "leg_bulgarian", name: "Sentadilla búlgara", block: "Pierna", family: "Dominante rodilla unilateral",
    movementPattern: "Sentadilla unilateral", compatibleRoles: ["Principal", "Complementario"],
    equipment: "Peso corporal/mancuernas/barra", loadSource: "Corporal+opcional", laterality: "Unilateral",
    primaryMuscle: "Cuádriceps/glúteos", secondaryMuscles: [{ muscle: "Ambos relevantes", coefficient: 0 }],
    accessibility: "Media", strengthRequirement: "Media", scalability: "Alta",
    stability: "Media", fatigueCost: "Media-Alta", progressionSuitability: "Alta",
    nearFailureSuitability: "Media-Alta", repRangeV1: [6, 15],
    restRangeSeconds: [90, 180], setupCost: "Medio",
    executionTimeCost: "Alto", densitySuitability: "Baja-Media", substitutionFamily: "Unilateral rodilla",
  },
  {
    id: "leg_static_lunge", name: "Zancada estática", block: "Pierna", family: "Dominante rodilla unilateral",
    movementPattern: "Zancada", compatibleRoles: ["Principal", "Complementario"],
    equipment: "Peso corporal/mancuernas", loadSource: "Corporal+opcional", laterality: "Unilateral",
    primaryMuscle: "Cuádriceps/glúteos", secondaryMuscles: [{ muscle: "Ambos relevantes", coefficient: 0 }],
    accessibility: "Media-Alta", strengthRequirement: "Baja-Media", scalability: "Alta",
    stability: "Media", fatigueCost: "Media", progressionSuitability: "Alta",
    nearFailureSuitability: "Media-Alta", repRangeV1: [8, 15],
    restRangeSeconds: [90, 180], setupCost: "Bajo",
    executionTimeCost: "Alto", densitySuitability: "Media", substitutionFamily: "Unilateral rodilla",
  },
  {
    id: "leg_walking_lunge", name: "Zancada caminando", block: "Pierna", family: "Dominante rodilla unilateral",
    movementPattern: "Zancada", compatibleRoles: ["Complementario"],
    equipment: "Peso corporal/mancuernas", loadSource: "Corporal+opcional", laterality: "Alterno",
    primaryMuscle: "Cuádriceps/glúteos", secondaryMuscles: [{ muscle: "Ambos relevantes", coefficient: 0 }],
    accessibility: "Media", strengthRequirement: "Baja-Media", scalability: "Alta",
    stability: "Media", fatigueCost: "Media-Alta", progressionSuitability: "Media-Alta",
    nearFailureSuitability: "Media-Alta", repRangeV1: [8, 20],
    restRangeSeconds: [90, 180], setupCost: "Medio",
    executionTimeCost: "Alto", densitySuitability: "Baja-Media", substitutionFamily: "Unilateral rodilla",
    motorNotes: "Requiere espacio",
  },
  {
    id: "leg_stepup", name: "Step-up", block: "Pierna", family: "Dominante rodilla unilateral",
    movementPattern: "Step", compatibleRoles: ["Complementario"],
    equipment: "Cajón/banco+carga", loadSource: "Corporal+opcional", laterality: "Unilateral",
    primaryMuscle: "Cuádriceps/glúteos", secondaryMuscles: [{ muscle: "Ambos relevantes", coefficient: 0 }],
    accessibility: "Media", strengthRequirement: "Baja-Media", scalability: "Alta",
    stability: "Media", fatigueCost: "Media", progressionSuitability: "Alta",
    nearFailureSuitability: "Media-Alta", repRangeV1: [8, 15],
    restRangeSeconds: [90, 180], setupCost: "Medio",
    executionTimeCost: "Alto", densitySuitability: "Media", substitutionFamily: "Unilateral rodilla",
    motorNotes: "Superficie estable conocida",
  },
  {
    id: "ham_barbell_rdl", name: "RDL barra", block: "Isquios", family: "Bisagra cadera",
    movementPattern: "Bisagra", compatibleRoles: ["Principal"],
    equipment: "Barra", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Isquios", secondaryMuscles: [{ muscle: "Glúteos", coefficient: 0 }, { muscle: "erectores estabilizan", coefficient: 0 }],
    accessibility: "Media", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Baja-Media", fatigueCost: "Alta", progressionSuitability: "Alta",
    nearFailureSuitability: "Media", repRangeV1: [5, 12],
    restRangeSeconds: [120, 240], setupCost: "Medio",
    executionTimeCost: "Medio", densitySuitability: "Baja", substitutionFamily: "Bisagra cadera",
  },
  {
    id: "ham_db_rdl", name: "RDL mancuernas", block: "Isquios", family: "Bisagra cadera",
    movementPattern: "Bisagra", compatibleRoles: ["Principal", "Complementario"],
    equipment: "Mancuernas", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Isquios", secondaryMuscles: [{ muscle: "Glúteos", coefficient: 0 }],
    accessibility: "Media", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Media", fatigueCost: "Media-Alta", progressionSuitability: "Alta",
    nearFailureSuitability: "Media-Alta", repRangeV1: [6, 15],
    restRangeSeconds: [120, 180], setupCost: "Bajo",
    executionTimeCost: "Medio", densitySuitability: "Baja-Media", substitutionFamily: "Bisagra cadera",
  },
  {
    id: "ham_seated_curl", name: "Curl femoral sentado", block: "Isquios", family: "Flexión rodilla",
    movementPattern: "Flexión rodilla", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Máquina", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Isquios", secondaryMuscles: [],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [8, 20],
    restRangeSeconds: [60, 120], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Flexión rodilla",
  },
  {
    id: "ham_lying_curl", name: "Curl femoral tumbado", block: "Isquios", family: "Flexión rodilla",
    movementPattern: "Flexión rodilla", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Máquina", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Isquios", secondaryMuscles: [],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [8, 20],
    restRangeSeconds: [60, 120], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Flexión rodilla",
  },
  {
    id: "ham_single_curl", name: "Curl femoral unilateral/de pie", block: "Isquios", family: "Flexión rodilla",
    movementPattern: "Flexión rodilla", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Máquina/polea específica", loadSource: "Externa", laterality: "Unilateral",
    primaryMuscle: "Isquios", secondaryMuscles: [],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [8, 20],
    restRangeSeconds: [60, 120], setupCost: "Medio",
    executionTimeCost: "Alto", densitySuitability: "Media-Alta", substitutionFamily: "Flexión rodilla",
  },
  {
    id: "ham_back_extension", name: "Extensión lumbar", block: "Isquios", family: "Extensión cadera/tronco",
    movementPattern: "Bisagra/extensión", compatibleRoles: ["Complementario"],
    equipment: "Banco romano", loadSource: "Corporal+opcional", laterality: "Bilateral",
    primaryMuscle: "Erectores/glúteos", secondaryMuscles: [{ muscle: "Isquios", coefficient: 0 }],
    accessibility: "Media", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Media", fatigueCost: "Media", progressionSuitability: "Media-Alta",
    nearFailureSuitability: "Media", repRangeV1: [8, 20],
    restRangeSeconds: [60, 120], setupCost: "Medio",
    executionTimeCost: "Bajo", densitySuitability: "Media", substitutionFamily: "Extensión cadera/tronco",
    motorNotes: "Énfasis depende de ejecución",
  },
  {
    id: "glute_barbell_hipthrust", name: "Hip thrust barra", block: "Glúteos", family: "Extensión cadera",
    movementPattern: "Extensión cadera", compatibleRoles: ["Principal"],
    equipment: "Barra+banco", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Glúteos", secondaryMuscles: [{ muscle: "Isquios secundarios", coefficient: 0 }],
    accessibility: "Media", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Media", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [6, 15],
    restRangeSeconds: [90, 180], setupCost: "Alto",
    executionTimeCost: "Medio", densitySuitability: "Media", substitutionFamily: "Extensión cadera",
  },
  {
    id: "glute_machine_hipthrust", name: "Hip thrust máquina", block: "Glúteos", family: "Extensión cadera",
    movementPattern: "Extensión cadera", compatibleRoles: ["Principal"],
    equipment: "Máquina", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Glúteos", secondaryMuscles: [{ muscle: "Isquios secundarios", coefficient: 0 }],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Media", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [6, 15],
    restRangeSeconds: [90, 180], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Extensión cadera",
  },
  {
    id: "glute_bridge", name: "Puente glúteos peso corporal", block: "Glúteos", family: "Extensión cadera",
    movementPattern: "Extensión cadera", compatibleRoles: ["Principal", "Complementario"],
    equipment: "Peso corporal", loadSource: "Corporal+opcional", laterality: "Bilateral",
    primaryMuscle: "Glúteos", secondaryMuscles: [{ muscle: "Isquios secundarios", coefficient: 0 }],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja", progressionSuitability: "Media",
    nearFailureSuitability: "Alta", repRangeV1: [10, 30],
    restRangeSeconds: [60, 120], setupCost: "Mínimo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Extensión cadera",
  },
  {
    id: "glute_kickback", name: "Patada glúteo polea", block: "Glúteos", family: "Extensión cadera",
    movementPattern: "Extensión cadera", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Polea", loadSource: "Externa", laterality: "Unilateral",
    primaryMuscle: "Glúteos", secondaryMuscles: [],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja", progressionSuitability: "Media",
    nearFailureSuitability: "Alta", repRangeV1: [10, 20],
    restRangeSeconds: [60, 120], setupCost: "Medio",
    executionTimeCost: "Alto", densitySuitability: "Media-Alta", substitutionFamily: "Extensión cadera aislada",
  },
  {
    id: "glute_abduction_machine", name: "Abducción máquina", block: "Glúteos", family: "Abducción cadera",
    movementPattern: "Abducción", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Máquina", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Glúteo medio/min", secondaryMuscles: [],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [10, 25],
    restRangeSeconds: [60, 120], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Abducción cadera",
  },
  {
    id: "glute_abduction_cable", name: "Abducción polea", block: "Glúteos", family: "Abducción cadera",
    movementPattern: "Abducción", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Polea", loadSource: "Externa", laterality: "Unilateral",
    primaryMuscle: "Glúteo medio/min", secondaryMuscles: [],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Media-Alta", fatigueCost: "Baja", progressionSuitability: "Media",
    nearFailureSuitability: "Alta", repRangeV1: [10, 25],
    restRangeSeconds: [60, 120], setupCost: "Medio",
    executionTimeCost: "Alto", densitySuitability: "Media-Alta", substitutionFamily: "Abducción cadera",
  },
  {
    id: "calf_standing_machine", name: "Gemelo de pie máquina", block: "Gemelos", family: "Flexión plantar",
    movementPattern: "Flexión plantar", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Máquina", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Gemelos/gastrocnemio", secondaryMuscles: [],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [8, 20],
    restRangeSeconds: [60, 120], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Flexión plantar extendida",
  },
  {
    id: "calf_seated", name: "Gemelo sentado", block: "Gemelos", family: "Flexión plantar",
    movementPattern: "Flexión plantar", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Máquina", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Gemelos/sóleo", secondaryMuscles: [],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [10, 25],
    restRangeSeconds: [60, 120], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Flexión plantar flexionada",
  },
  {
    id: "calf_legpress", name: "Gemelo prensa", block: "Gemelos", family: "Flexión plantar",
    movementPattern: "Flexión plantar", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Prensa", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Gemelos", secondaryMuscles: [],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [8, 25],
    restRangeSeconds: [60, 120], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Flexión plantar extendida",
  },
  {
    id: "calf_bodyweight", name: "Gemelo de pie peso corporal", block: "Gemelos", family: "Flexión plantar",
    movementPattern: "Flexión plantar", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Peso corporal", loadSource: "Corporal+opcional", laterality: "Bilateral/unilateral",
    primaryMuscle: "Gemelos", secondaryMuscles: [],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja", progressionSuitability: "Media",
    nearFailureSuitability: "Alta", repRangeV1: [0, 0],
    restRangeSeconds: [60, 120], setupCost: "Mínimo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Flexión plantar",
  },
  {
    id: "forearm_reverse_curl", name: "Curl inverso", block: "Antebrazo", family: "Flexión codo pronada",
    movementPattern: "Flexión codo", compatibleRoles: ["Complementario", "Aislamiento"],
    equipment: "Barra/EZ/polea", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Braquiorradial/extensores", secondaryMuscles: [{ muscle: "Bíceps secundario", coefficient: 0 }],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [8, 20],
    restRangeSeconds: [60, 120], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Antebrazo",
  },
  {
    id: "forearm_wrist_curl", name: "Curl muñeca", block: "Antebrazo", family: "Flexión muñeca",
    movementPattern: "Flexión muñeca", compatibleRoles: ["Aislamiento"],
    equipment: "Mancuerna/barra/polea", loadSource: "Externa", laterality: "Variable",
    primaryMuscle: "Flexores antebrazo", secondaryMuscles: [],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja", progressionSuitability: "Media-Alta",
    nearFailureSuitability: "Alta", repRangeV1: [10, 25],
    restRangeSeconds: [45, 90], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Flexión muñeca",
  },
  {
    id: "forearm_wrist_extension", name: "Extensión muñeca", block: "Antebrazo", family: "Extensión muñeca",
    movementPattern: "Extensión muñeca", compatibleRoles: ["Aislamiento"],
    equipment: "Mancuerna/barra/polea", loadSource: "Externa", laterality: "Variable",
    primaryMuscle: "Extensores antebrazo", secondaryMuscles: [],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja", progressionSuitability: "Media-Alta",
    nearFailureSuitability: "Alta", repRangeV1: [10, 25],
    restRangeSeconds: [45, 90], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Extensión muñeca",
  },
  {
    id: "core_machine_crunch", name: "Crunch máquina", block: "Core", family: "Flexión tronco",
    movementPattern: "Flexión tronco", compatibleRoles: ["Complementario"],
    equipment: "Máquina", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Recto abdominal", secondaryMuscles: [],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [8, 20],
    restRangeSeconds: [60, 120], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Flexión tronco",
  },
  {
    id: "core_cable_crunch", name: "Crunch polea", block: "Core", family: "Flexión tronco",
    movementPattern: "Flexión tronco", compatibleRoles: ["Complementario"],
    equipment: "Polea", loadSource: "Externa", laterality: "Bilateral",
    primaryMuscle: "Recto abdominal", secondaryMuscles: [],
    accessibility: "Media-Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Media-Alta", fatigueCost: "Baja", progressionSuitability: "Alta",
    nearFailureSuitability: "Alta", repRangeV1: [8, 20],
    restRangeSeconds: [60, 120], setupCost: "Medio",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Flexión tronco",
  },
  {
    id: "core_floor_crunch", name: "Crunch suelo", block: "Core", family: "Flexión tronco",
    movementPattern: "Flexión tronco", compatibleRoles: ["Complementario"],
    equipment: "Peso corporal", loadSource: "Corporal", laterality: "Bilateral",
    primaryMuscle: "Recto abdominal", secondaryMuscles: [],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Media",
    stability: "Alta", fatigueCost: "Baja", progressionSuitability: "Media",
    nearFailureSuitability: "Alta", repRangeV1: [10, 30],
    restRangeSeconds: [45, 90], setupCost: "Mínimo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Flexión tronco",
  },
  {
    id: "core_leg_raise", name: "Elevación rodillas/piernas", block: "Core", family: "Control pelvis/elevación",
    movementPattern: "Elevación piernas", compatibleRoles: ["Complementario"],
    equipment: "Peso corporal", loadSource: "Corporal", laterality: "Bilateral",
    primaryMuscle: "Core", secondaryMuscles: [{ muscle: "Flexores cadera", coefficient: 0 }],
    accessibility: "Media", strengthRequirement: "Media", scalability: "Alta",
    stability: "Media", fatigueCost: "Media", progressionSuitability: "Media",
    nearFailureSuitability: "Media-Alta", repRangeV1: [6, 20],
    restRangeSeconds: [60, 120], setupCost: "Bajo",
    executionTimeCost: "Bajo", densitySuitability: "Media-Alta", substitutionFamily: "Elevación piernas/core",
  },
  {
    id: "core_plank", name: "Plancha", block: "Core", family: "Anti-extensión",
    movementPattern: "Estabilidad", compatibleRoles: ["Estabilidad", "Control"],
    equipment: "Peso corporal", loadSource: "Corporal", laterality: "Bilateral",
    primaryMuscle: "Core anterior", secondaryMuscles: [],
    accessibility: "Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja", progressionSuitability: "Media",
    nearFailureSuitability: "Media-Alta", repRangeV1: [20, 60],
    restRangeSeconds: [45, 90], setupCost: "Mínimo",
    executionTimeCost: "Bajo", densitySuitability: "Alta", substitutionFamily: "Anti-extensión",
    motorNotes: "Progresar dificultad, no solo tiempo",
  },
  {
    id: "core_side_plank", name: "Plancha lateral", block: "Core", family: "Estabilidad lateral",
    movementPattern: "Estabilidad", compatibleRoles: ["Estabilidad", "Control"],
    equipment: "Peso corporal", loadSource: "Corporal", laterality: "Unilateral",
    primaryMuscle: "Core lateral", secondaryMuscles: [],
    accessibility: "Media-Alta", strengthRequirement: "Baja-Media", scalability: "Alta",
    stability: "Media-Alta", fatigueCost: "Baja", progressionSuitability: "Media",
    nearFailureSuitability: "Media-Alta", repRangeV1: [15, 60],
    restRangeSeconds: [45, 90], setupCost: "Mínimo",
    executionTimeCost: "Medio", densitySuitability: "Alta", substitutionFamily: "Estabilidad lateral",
  },
  {
    id: "core_deadbug", name: "Dead bug", block: "Core", family: "Anti-extensión/control",
    movementPattern: "Estabilidad", compatibleRoles: ["Estabilidad", "Control"],
    equipment: "Peso corporal", loadSource: "Corporal", laterality: "Contralateral",
    primaryMuscle: "Core", secondaryMuscles: [],
    accessibility: "Media", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja", progressionSuitability: "Media",
    nearFailureSuitability: "No prioritario", repRangeV1: [6, 15],
    restRangeSeconds: [45, 90], setupCost: "Mínimo",
    executionTimeCost: "Medio", densitySuitability: "Alta", substitutionFamily: "Anti-extensión/control",
    motorNotes: "No orientar a fallo",
  },
  {
    id: "core_pallof", name: "Pallof press", block: "Core", family: "Anti-rotación",
    movementPattern: "Estabilidad", compatibleRoles: ["Estabilidad", "Control"],
    equipment: "Polea/banda segura", loadSource: "Externa", laterality: "Por lados",
    primaryMuscle: "Core", secondaryMuscles: [],
    accessibility: "Media-Alta", strengthRequirement: "Baja", scalability: "Alta",
    stability: "Alta", fatigueCost: "Baja", progressionSuitability: "Media",
    nearFailureSuitability: "No prioritario", repRangeV1: [8, 15],
    restRangeSeconds: [45, 90], setupCost: "Medio",
    executionTimeCost: "Medio", densitySuitability: "Alta", substitutionFamily: "Anti-rotación",
    motorNotes: "No inventar anclajes",
  },
];

export const libraryById = new Map(LIBRARY.map(e => [e.id, e]));
export const libraryByBlock = (block: string) => LIBRARY.filter(e => e.block === block);

